// <auto-generated />
using Cobit19.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cobit19.Migrations.Tablas
{
    [DbContext(typeof(DbContextTablas))]
    [Migration("20240616164037_InitialCreateForTablas")]
    partial class InitialCreateForTablas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cobit19.Data.MetasAlineamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AG01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG07")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG08")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG09")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AG13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaGobierno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetasAlineamientos");
                });

            modelBuilder.Entity("Cobit19.Data.MetasEmpresariales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EG01")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG02")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG03")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG04")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG05")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG06")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG07")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG08")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG09")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EG13")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaAlineamiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetasEmpresarialess");
                });
#pragma warning restore 612, 618
        }
    }
}
